[config]
default_to_workspace = false

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.watch]
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.watch.env]
GENKO_DEVELOPMENT_WATCH_MODE = "1"

[tasks.test]
command = "cargo"
args = ["test", "--offline", "--all"]

[tasks.test-target]
command = "cargo"
args = ["test", "--offline", "--target", "${@}"]

[tasks.new]
command = "./scripts/new_crate.py"
args = ["${@}"]

[tasks.configure]
command = "nvim"
args = ["${HOME}/.config/genko/settings.json"]

[tasks.bug]
command = "gh"
args = ["issue", "create", "--template", "bug_report.md"]

[tasks.feature]
command = "gh"
args = ["issue", "create", "--template", "feature_request.md"]
