[package]
name = "menu"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "menu"
path = "src/menu.rs"

[dependencies]
document = { workspace = true }
gpui = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls"
] }
semver = { workspace = true }
serde = { workspace = true }
title_bar = { workspace = true }
ui = { workspace = true }
