[package]
name = "soukou"
version = "0.1.0"
edition = "2024"

[package.metadata.bundle]
icon = ["resources/AppIcon.icns"]
resources = ["resources/AppIcon.icns"]
identifier = "dev.monj.soukou"
name = "草稿"
osx_minimum_system_version = "11.0"
osx_info_plist_exts = ["resources/info/*"]

[[bin]]
name = "soukou"
path = "src/main.rs"

[build-dependencies]
embed-resource = "3"

[dependencies]
bottom_bar = { workspace = true }
document_export = { workspace = true }
dotenvy = "0.15"
editor = { workspace = true, features = ["embedded-ipadic"] }
env = { workspace = true }
futures = "0.3"
gpui = { workspace = true }
gpui_platform = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
richtext = { workspace = true }
rope = { workspace = true }
semver = "1"
serde = { workspace = true }
serde_json = { workspace = true }
settings = { workspace = true }
theme = { workspace = true }
title_bar = { workspace = true }
ui = { workspace = true }
url = "2"
urlencoding = "2"
xdg = { workspace = true }
