[package]
name = "soukou"
version = "0.3.2"
edition = "2024"

[package.metadata.bundle]
icon = ["resources/AppIcon.icns"]
resources = ["resources/AppIcon.icns"]
identifier = "dev.monj.soukou"
name = "草稿"
osx_minimum_system_version = "11.0"
osx_info_plist_exts = ["crates/soukou/resources/info/*"]

[[bin]]
name = "soukou"
path = "src/main.rs"

[dependencies]
auth = { workspace = true }
bottom_bar = { workspace = true }
document = { workspace = true }
dotenvy = { workspace = true }
editor = { workspace = true, features = ["embedded-ipadic"] }
env = { workspace = true }
futures = { workspace = true }
gpui = { workspace = true }
gpui_platform = { workspace = true }
icons = { workspace = true }
keymap = { workspace = true }
menu = { workspace = true }
rich_text = { workspace = true }
rope = { workspace = true }
settings = { workspace = true }
theme = { workspace = true }
title_bar = { workspace = true }
ui = { workspace = true }
unicode-segmentation = { workspace = true }
workspace = { workspace = true }

[build-dependencies]
embed-resource = "3"
