[package]
name = "editor"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[lib]
name = "editor"

[dependencies]
gpui = { workspace = true }
icons = { workspace = true }
rope = { workspace = true }
rich_text = { workspace = true }
settings = { workspace = true }
theme = { workspace = true }
ui = { workspace = true }
env = { workspace = true }
lindera = "2.3.4"

[features]
default = []
embedded-ipadic = ["lindera/embed-ipadic"]
