name: License

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check licenses sources
          arguments: --locked
